<?php
	/**
	 * Stop script when the file is called directly.
	 */
	if(!function_exists("add_action")) {
		return false;
	}

	/**
	 * Initializes plugin's setting page.
	 */
	function init_admin_settings_page() {
		/** Creates a new page on the admin interface */
		add_options_page(__("IMDb Connector settings"), "IMDb Connector", "manage_options", "imdb-connector", "build_admin_settings_page");
	}

	add_action("admin_menu", "init_admin_settings_page");

	/**
	 * Builds the plugin's settings page.
	 */
	function build_admin_settings_page() {
		$saved = false;
		/** Save settings */
		if(isset($_POST["saved"])) {
			foreach(get_imdb_connector_settings() as $setting => $value) {
				$field = str_replace("imdb_connector_", "", $setting);
				/** Skip setting that hasn't been set */
				if(!isset($_POST[$field])) {
					continue;
				}
				update_option($setting, $_POST[$field]);
			}
			$saved = true;
		}
		?>
		<div class="wrap imdb-connector-settings">
			<h2><?php echo __("Settings", "imdb_connector") . " › " . __("IMDb Connector", "imdb_connector"); ?></h2>
			<?php if($saved) { ?>
				<div class="updated settings-error"><p><?php _e("Settings have been saved.", "imdb_connector"); ?></p></div>
			<?php } ?>
			<form method="post" action="">
				<input type="hidden" id="remote-actions-url" value="<?php the_imdb_connector_url(); ?>includes/remote-actions.php" />
				<table class="form-table">
					<tbody>
						<tr id="allow-caching-row">
							<?php
								$cache_path         = get_imdb_connector_cache_path();
								$invalid_cache_path = "";
								if(!is_dir($cache_path) && !mkdir($cache_path)) {
									$invalid_cache_path = ' disabled="disabled"';
								}
							?>
							<th scope="row"><label for="allow_caching_on"><?php _e("Caching", "imdb_connector"); ?></label>
							</th>
							<td>
								<input type="radio" name="allow_caching" id="allow_caching_on" value="on"<?php imdb_connector_check_setting("allow_caching", "on");
									echo $invalid_cache_path; ?>  />
								<label for="allow_caching_on"><?php _e("On", "imdb_connector"); ?></label>
								<input type="radio" name="allow_caching" id="allow_caching_off" value="off"<?php imdb_connector_check_setting("allow_caching", "off");
									echo $invalid_cache_path; ?> />
								<label for="allow_caching_off"><?php _e("Off", "imdb_connector"); ?></label>
								<p id="delete-cache-container">
									<input type="button" value="<?php _e("Delete cache", "imdb_connector"); ?>" id="delete-cache" class="button" title="<?php _e("Delete all cache files generated by IMDb Connector", "imdb_connector"); ?>" />
									<img src="<?php the_imdb_connector_url(); ?>images/loading.gif" alt="<?php _e("Loading...", "imdb_connector"); ?>" id="delete-cache-loading-icon" hidden="hidden" />
									<span class="message success" hidden="hidden"><?php echo sprintf(__("%s files successfully deleted.", "imdb_connector"), '<span id="deleted-files-number">0</span>'); ?></span>
								</p>
								<p class="description"><?php _e("Allows IMDb Connector to cache movie details and covers for faster access (recommended).", "imdb_connector"); ?></p>
								<?php if($invalid_cache_path) { ?>
									<div id="invalid-directory">
										<p class="message error">
											<?php
												_e("Caching has been disabled because the following directory does not exist<br />and could not be created:", "imdb_connector");
											?>
										</p>
										<code><?php echo get_imdb_connector_cache_url(); ?></code>
									</div>
								<?php } ?>
							</td>
						</tr>
						<tr>
							<th scope="row">
								<label for="allow_shortcodes_on"><?php _e("Shortcodes", "imdb_connector"); ?></label>
							</th>
							<td>
								<input type="radio" name="allow_shortcodes" id="allow_shortcodes_on" value="on"<?php imdb_connector_check_setting("allow_shortcodes", "on"); ?> />
								<label for="allow_shortcodes_on"><?php _e("On", "imdb_connector"); ?></label>
								<input type="radio" name="allow_shortcodes" id="allow_shortcodes_off" value="off"<?php imdb_connector_check_setting("allow_shortcodes", "off"); ?> />
								<label for="allow_shortcodes_off"><?php _e("Off", "imdb_connector"); ?></label>
								<p class="description">
									<?php echo sprintf(__('Provides <a href="%s" target="_blank">shortcodes</a> to easily insert movie details into your posts or pages.<br />For a full list of available parameters, please see the <a href="http://www.koljanolte.com/wordpress/plugins/imdb-connector/" target="_blank">official documentation</a>.', "imdb_connector"), "http://codex.wordpress.org/Shortcode_API"); ?>
								</p>
								<p class="description">
									<a href="#" id="show-shortcode-examples"><?php _e("Show examples", "imdb_connector"); ?></a>
								</p>
								<ul id="shortcode-examples" hidden="hidden">
									<li>
										<p><code>[imdb_movie_detail title="The Shawshank Redemption" detail="year"]</code></p>
										<p><?php _e('Displays the release year of <em>The Shawshank Redemption</em>.', "imdb_connector"); ?></p>
									</li>
									<li>
										<p><code>[imdb_movie_detail title="tt0075314" detail="director"]</code></p>
										<p><?php _e('Displays the director of <em>Taxi Driver</em>.', "imdb_connector"); ?></p>
									</li>
								</ul>
							</td>
						</tr>
						<tr>
							<th scope="row">
								<label for="allow_default_styles_on"><?php _e("Use default widgets style", "imdb_connector"); ?></label>
							</th>
							<td>
								<input type="radio" name="allow_default_styles" id="allow_default_styles_on" value="on"<?php imdb_connector_check_setting("allow_default_styles", "on"); ?> />
								<label for="allow_default_styles_on"><?php _e("On", "imdb_connector"); ?></label>
								<input type="radio" name="allow_default_styles" id="allow_default_styles_off" value="off"<?php imdb_connector_check_setting("allow_default_styles", "off"); ?> />
								<label for="allow_default_styles_off"><?php _e("Off", "imdb_connector"); ?></label>
								<p class="description">
									<?php echo sprintf(__('Makes IMDb Connector use its default CSS styles for widgets<br />defined in <a href="%s" target="_blank"><code>widgets.css</code></a>.', "imdb_connector"), get_imdb_connector_url() . "styles/widgets.css"); ?>
								</p>
							</td>
						</tr>
						<tr id="row-debug-mode">
							<th><label for="debug-mode-on"><?php _e("Debug mode", "imdb_connector"); ?></label></th>
							<td>
								<input type="radio" id="debug-mode-on" name="debug_mode" value="on"<?php imdb_connector_check_setting("debug_mode", "on"); ?> />
								<label for="debug-mode-on"><?php _e("On", "imdb_connector"); ?></label>
								<input type="radio" id="debug-mode-off" name="debug_mode" value="off"<?php imdb_connector_check_setting("debug_mode", "off"); ?> />
								<label for="debug-mode-off"><?php _e("Off", "imdb_connector"); ?></label>
								<p class="description"><?php _e("Displays errors and warnings.", "imdb_connector"); ?></p>
							</td>
						</tr>
					</tbody>
				</table>
				<p>
					<br />
					<input type="hidden" name="saved" value="true" />
					<input type="submit" name="save_settings" class="button-primary" value="<?php _e("Save changes", "imdb_connector"); ?>" />
				</p>
				<p>
					<small><?php _e('Found an error? Help making IMDb Connector better by <a href="http://www.wordpress.org/support/plugin/imdb-connector#postform" target="_blank">quickly reporting the bug</a>.', "imdb_connector"); ?></small>
				</p>
			</form>
		</div>
	<?php
	}